ALTER TABLE teams DROP FOREIGN KEY teams_ibfk_1;
ALTER TABLE users MODIFY id VARCHAR(255) NOT NULL;
ALTER TABLE teams MODIFY leader_id VARCHAR(255) NOT NULL;
ALTER TABLE teams ADD CONSTRAINT FK_leader_id FOREIGN KEY (leader_id) REFERENCES users(id);