ALTER TABLE teams DROP FOREIGN KEY FK_leader_id;
ALTER TABLE users MODIFY id INT UNSIGNED NOT NULL;
ALTER TABLE teams MODIFY leader_id INT UNSIGNED NOT NULL;
ALTER TABLE teams ADD CONSTRAINT FK_leader_id FOREIGN KEY (leader_id) REFERENCES users(id);